### ISSUE TITLE
[BUG] On initial load the index management plugin page is empty 

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/index-management-dashboards-plugin#1038]
**What is the bug?**
On the initial load of the plugin page, it shows empty with no errors 
http://localhost:5601/app/opensearch_index_management_dashboards#/

![Screenshot from 2024-04-15 22-17-05](https://github.com/opensearch-project/index-management-dashboards-plugin/assets/17714150/fb3c616c-c557-4d45-9cf9-de3ba61cd830)

However, enter the following url with subpath, would show the page, but the default is local cluster http://localhost:5601/app/opensearch_index_management_dashboards#/index-policies

**How can one reproduce the bug?**
1. yarn start to spin off osd and the plugin
2. Click on 'index management'
3. See empty page

**What is the expected behavior?**
The plugin should show a landing page with subpath /index-policies, similar to https://playground.opensearch.org/app/opensearch_index_management_dashboards#/index-policies?from=0&search=&size=20&sortDirection=desc&sortField=id

Default data source is introduced and set by data source picker as call back, the default data source id should be used instead of local cluster as default

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by BionIT** [comment]
@RamakrishnaChilaka while pulling from main, I found the issue described above, could you help to resolve?

**Comment by RamakrishnaChilaka** [comment]
Thanks Lu, for reporting the bug. I acknowledge that this is indeed a bug, this should be fixed with https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1039

**Comment by RamakrishnaChilaka** [comment]
@BionIT, closing this as https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1039 PR is merged and I have verified that issue is fixed. Kindly, reopen the issue if you find that issue is not fixed.
