### ISSUE TITLE
[BUG] Hide local cluster would break index management page and should use default data source instead

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/index-management-dashboards-plugin#1041]
**What is the bug?**
Setting the following in yaml config
```
data_source.enabled: true
data_source.hideLocalCluster: true
```
would see the following
![Screenshot 2024-04-17 at 10 35 17 AM](https://github.com/opensearch-project/index-management-dashboards-plugin/assets/17714150/6237d88b-266e-476f-bc6d-98c6f3b6c488)

I think it is due to the url query param is using empty data source id as input, on first time page load, since data source id is not available until the data source component is mounted, thus we can avoid having it in the url on first load, and once the component is loaded, then the data source id can be added to the url. 

**How can one reproduce the bug?**
1. Enabled data source plugin, and set `data_source.hideLocalCluster: true` in the yaml
2. Go to index management
3. See error

**What is the expected behavior?**
Default data source is introduced in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6276, and the data source component will acquire the default data source as the top choice if no valid action option is passed in. The data source chosen by the data source component should be the one that gets rendered

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by BionIT** [comment]
@RamakrishnaChilaka thanks for fixing the routing issue! Could you take a look at this one as well?

**Comment by RamakrishnaChilaka** [comment]
@BionIT, we are getting `[]` empty array from `onSelectedDataSources` callback.

**Comment by BionIT** [comment]
@RamakrishnaChilaka could you check what is the actionOption input pass into the selectable when the yaml config is turned on and off? 

I noticed that in future playground, the page forces to use local cluster while default cluster exists. Check the link to index management https://future.playground.opensearch.org/app/opensearch_index_management_dashboards#/index-policies and then check security plugin page https://future.playground.opensearch.org/app/security-dashboards-plugin which shows the current default data source on initial load

**Comment by BionIT** [comment]
Awesome, 👍

**Comment by RamakrishnaChilaka** [comment]
Closing, as https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1042 is merged and verified by testing locally. Kindly, reopen if you find it is not fixed yet.
