### ISSUE TITLE
[BUG] periodic schedule interval or cron are not implemented 

### ISSUE THREAD

**Issue by avishai-cyronix** [opensearch-project/index-management-dashboards-plugin#107]
**Describe the bug**
When creating a new Transform Job with periodic schedule `interval` or `cron`, after only a single run the job state become `disabled`.

**Other plugins installed**
- Query Workbench
- Reporting
- Notebooks
- Alerting
- Anomaly Detection
- Trace Analytics
- Index Management

**To Reproduce**
1. Go to `Index Management`
2. Select `Transform jobs`
3. Create a transform job with schedule to run every minute
4. When the transform job `complete`, the job state changes to `disabled`

**Expected behavior**
Transform job should run periodically as defined in the schedule section of the job.

**Screenshots**
![image](https://user-images.githubusercontent.com/89780925/136943312-8b78dd13-7695-45ad-b091-bfe25155e8ed.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome,
 - Version: 94.0.4606.71

**Comment by JeffBolle** [comment]
Is there still no ETA on this?  For my use case does this not only render Transforms useless, but it blocks our transition to OpenSearch from ElasticSearch. I see that the PR is still awaiting review. When is it expected to be reviewed and merged?

**Comment by sikhote** [comment]
@JeffBolle FYI from the backend PR...hope this helps.

> In case someone else face the same issue, it is resolved. You just need to add the parameter "continuous" : true.
