### ISSUE TITLE
Failed to create policy: [parsing_exception] Failed to parse object: expecting token of type [START_OBJECT] but found [START_ARRAY], with { line=1 & col=512 }

### ISSUE THREAD

**Issue by lsy1990** [opensearch-project/index-management-dashboards-plugin#110]
I want to create a policy to manage index.
After the index pattern and state have been setted, I do create command ,and it failed.
The errors  is bellow:
Failed to create policy: [parsing_exception] Failed to parse object: expecting token of type [START_OBJECT] but found [START_ARRAY], with { line=1 & col=512 }

Is there some error that I make a mistake to set policy parameter?
![image](https://user-images.githubusercontent.com/5174292/136929912-3deb4f5a-1d5b-428e-9747-197ae04041a0.png)

**Comment by dmpe** [comment]
Currently also facing this with OpenSearch 2.0. Currently, trying to setup notification email trigger `app/alerting#/monitors` and when clicking update, getting this error.

**Comment by dmpe** [comment]
> > Currently also facing this with OpenSearch 2.0. Currently, trying to setup notification email trigger `app/alerting#/monitors` and when clicking update, getting this error.
> 
> Hello! @dmpe would you be able to check out this: ;[opensearch-project/alerting-dashboards-plugin#254 (comment)](https://github.com/opensearch-project/alerting-dashboards-plugin/issues/254#issuecomment-1146311322)?

Yes ! Thank you and sorry for posting comment here. Feel free to remove/hide.
