### ISSUE TITLE
[BUG] Filtering by special characters is not always supported managed indices page

### ISSUE THREAD

**Issue by thalurur** [opensearch-project/index-management-dashboards-plugin#119]
**Describe the bug**
Managed indices page currently is using ~simple_query_string~ query-string internally to fetch the results for the posted string in the search bar. However, this is can be limiting as certain characters are reserved in the query. 
https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-query-string-query.html

e.g. `-` is reserved so searching with this returns nothing in the result. `.` is not supported returns no results

Fix:
Update query in the backend or update the query string to escape the reserved characters?

**Comment by thalurur** [comment]
Related:
* https://github.com/opensearch-project/index-management-dashboards-plugin/issues/117
* https://github.com/opensearch-project/index-management-dashboards-plugin/issues/112

**Comment by leeyun-amzn** [comment]
Index policies page also has the same behavior as managed indices page. This may be solved by similar approach on indices page to parse search string before passing into node API request
