### ISSUE TITLE
[BUG] can't create transform job in UI

### ISSUE THREAD

**Issue by arnitolog** [opensearch-project/index-management-dashboards-plugin#134]
**Describe the bug**
UI shows a blank page once I'm trying to select non-keyword or non-date fields in the transform job.
I see this behavior for double, integer, and text types of fields.

**Other plugins installed**
Only standard Opensearch plugins

**To Reproduce**
1. Go to Index Management/Transform jobs and create a new transform job
2. Select index with different types of data (double, keywords, integer)
3. Click on columns hidden to add a new one 
4. Select any non-keyword or non-date field
5. see the blank page

**Expected behavior**
The field is properly selected and available for transformation/aggregation

**Screenshots**
Working case: keyword field selected:
![image](https://user-images.githubusercontent.com/34036079/144056867-ec6db058-6571-451d-8ec0-d8c72681ea64.png)

Non-working case: I've tried to select a field with type double: 
![image](https://user-images.githubusercontent.com/34036079/144057407-6679d06a-61fc-46be-ab5b-b058a08f07bb.png)

The error I see in the dev tools in the browser for non-working case:
![image](https://user-images.githubusercontent.com/34036079/144057352-a7403f63-d4b9-45f0-a2dd-9f1614f9a32d.png)

**Desktop (please complete the following information):**
 - Opensearch Version 1.2.0

**Comment by thalurur** [comment]
The fix will be released in 2.0.0 version
