### ISSUE TITLE
[FEATURE] Add a button (in "Index Management" section?) to delete an index (if being admin)

### ISSUE THREAD

**Issue by q2dg** [opensearch-project/index-management-dashboards-plugin#142]
I miss this option a lot from Dashboard (comparting to Kibana.)
I think it's a very convenient feature (instead of having to go every time to "Dev console" and write _DELETE /whatever_)
Although I understant it'd be low priority
Thanks!

**Comment by ssi444** [comment]
Are you planning to implement this functionality and when?

**Comment by xluo-aws** [comment]
> 

We're working on add this feature as well as other operation feature(creaet/update/reindex, etc) to ISM dashboard plugin now, will try to release in Jan/Feb 2023.

**Comment by SuZhou-Joe** [comment]
This issue is a duplicate as https://github.com/opensearch-project/index-management-dashboards-plugin/issues/305, let's track the detail in that issue.
