### ISSUE TITLE
Error message in console 

### ISSUE THREAD

**Issue by thalurur** [opensearch-project/index-management-dashboards-plugin#143]
**Describe the bug**
When creating transform using dashboards seeing the following error in console

`
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-75XtnrpDA0UHDMcl7S8lvswryIOd0RqgacRh0AMOgdk='), or a nonce ('nonce-...') is required to enable inline execution.
`

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/6005951/154370900-0eb0f400-f3e1-47ac-92e3-ee2999fb29cd.png">

**Comment by dbbaughe** [comment]
https://github.com/elastic/kibana/issues/30468
