### ISSUE TITLE
Add more options to index management -> indices screen

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management-dashboards-plugin#154]
<a href="https://github.com/ict-one-nl"><img src="https://avatars.githubusercontent.com/u/2643715?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ict-one-nl](https://github.com/ict-one-nl)**
_Sunday Dec 27, 2020 at 12:14 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/365_

----

**Is your feature request related to a problem? Please describe.**
Deleting an index, updating it's settings, etc. would be nice to have here like Kibana from ElasticSearch itself.

**Describe the solution you'd like**

**Describe alternatives you've considered**
REST API is fine but a graphical interface would be nice as well.

**Additional context**

**Comment by xluo-aws** [comment]
We are working on a new feature to add those index operations(delete, create, update, reindex, etc) to ISM plugin page

**Comment by xluo-aws** [comment]
In release 2.5 and 2.6, we have released features to index management plugin UI to allow user create index, update index setting, add index mapping, open/close/delete/split/shrink/reindex. create/update alias/templates/data stream, etc.

**Comment by xluo-aws** [comment]
We plan to add index flush, refresh and clear cache in 2.8. If there is any other common index operations you want us to add on the UI, please leave a comment here.

**Comment by jasonrojas** [comment]
> We plan to add index flush, refresh and clear cache in 2.8. If there is any other common index operations you want us to add on the UI, please leave a comment here.

One thing I was thinking of while adding some notifications today was adding any customizations for the messaging that can include cluster name etc - when you manage multiple clusters, seeing all the notifications is great, but knowing where they came from would be better.
