### ISSUE TITLE
Add support for build version qualifiers.

### ISSUE THREAD

**Issue by dblock** [opensearch-project/index-management-dashboards-plugin#166]
Coming from https://github.com/opensearch-project/opensearch-build/issues/1632, add support for `-Dbuild.version_qualifier=`. 

The distribution build process now supports passing additional optional qualifiers other than the 3 digit versions, e.g. `2.0.0-alpha1`. Add the ability to pass additional qualifier to build scripts, and generate artifacts with a version that includes the qualifier.

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/opensearch-build/pull/1836

**Comment by kavilla** [comment]
Hello @downsrob, I see you are assigned tot his issue.

Unfortunately for OpenSearch Dashboards we don't have a nice build param as OpenSearch side has [yet](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1398). You will be able to build and connect successfully to OpenSearch Dashboards `yarn plugin_helpers build --opensearch-dashboards-version=2.0.0-rc1)` with an OSD plugin `2.0.0.0` but this will fail within the distribution build.

As for `2.0.0-rc1` we ask plugins to bump their `version` [[here]](https://github.com/opensearch-project/index-management-dashboards-plugin/blob/main/opensearch_dashboards.json#L3) to be `2.0.0.0-rc1` to be supported within the build distribution.

My opinion, is to leave `opensearchDashboardsVersion` untouched. You can then utilize OpenSearch Dashboards `main`. Within the build repo we build OpenSearch Dashboards and plugins with a qualifier. This will set OpenSearch Dashboards to be `2.0.0-rc1` and within plugins `"opensearchDashboardsVersion": "2.0.0-rc1"`. So it will be compatible and succeed in the building of distributions.

Let me know if you have any follow up questions.

Thanks!
