### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/index-management-dashboards-plugin#216]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by prudhvigodithi** [comment]
Hey @praveensameneni can you please post an update on this branching strategy?
Thank you
@dblock @bbarani @CEHENKLE

**Comment by bowenlan-amzn** [comment]
Created 2.x branch from main branch.

Will bump the main branch to 3.0 once IM backend bumps successfully https://github.com/opensearch-project/index-management/issues/416

**Comment by dblock** [comment]
There should be nothing blocking this rn. To close this issue:

- [ ] main is building 3.0
- [ ] 2.x is building next 2.x, which is currently 2.4.0
- [ ] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3

**Comment by bbarani** [comment]
@bowenlan-amzn re-tagging this issue for 2.4.0 release.

**Comment by bowenlan-amzn** [comment]
Will continue once IM backend bump 3.0 PR merged https://github.com/opensearch-project/index-management/pull/585

**Comment by bbarani** [comment]
@bowenlan-amzn @qreshi Can you provide updated status of this issue?

**Comment by bowenlan-amzn** [comment]
Will work on this once backend 3.0 PR finished https://github.com/opensearch-project/index-management/pull/585

**Comment by bowenlan-amzn** [comment]
Done!
