### ISSUE TITLE
[Cypress automation tests failing on ARM64]

### ISSUE THREAD

**Issue by praveensameneni** [opensearch-project/index-management-dashboards-plugin#35]
**Describe the bug**
Cypress integration tests on ARM64 are failing

**To Reproduce**
The below test is failing with Security and No Security
https://localhost:9200/index*,sample*,opensearch_dashboards*

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

   Error: connect ECONNREFUSED 127.0.0.1:9200
The request we sent was:

Method: DELETE
URL: https://localhost:9200/index*,sample*,opensearch_dashboards*

2. See error
1) Managed indices
       can edit rollover_alias
         "before each" hook for "successfully":
     AssertionError: Timed out retrying after 60000ms: Expected to find content: 'Rows per page' but never did.

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Managed indices`
      at Context.eval (http://172.31.24.166:5601/__cypress/tests?p=cypress/integration/managed_indices_spec.js:182:8)

**Expected behavior**
Successful run of the two failed tests.

**Desktop (please complete the following information):**
 - OS: ARM64

**Comment by thalurur** [comment]
This was addressed in this PR, to support custom endpoints in cypress tests even when security is enabled - https://github.com/opensearch-project/index-management-dashboards-plugin/pull/33
