### ISSUE TITLE
[BUG] OpenSearch Dashboard won't operate on a transform with corrupted name

### ISSUE THREAD

**Issue by alexmaurizio** [opensearch-project/index-management-dashboards-plugin#451]
**Describe the bug**
Not sure if I have to post this also on regular OpenSearch APIs repo, since it's a cross bug
On an older OpenSearch version (1.2) a Transform was created via APIs and it was never been able to be deleted, both from APIs and from Dashboard. Now I'm on 2.3 and still the same problem arises. I'm left with two "zombies" transform which cannot be manipulated or deleted

**To Reproduce**
Not possible to create a "with space ID" anymore. But this are the steps that fails when deleting
1. See full transform list - there is a trim in the dashboard somewhere, the name has no spaces. The transform shows regularly.
![image](https://user-images.githubusercontent.com/15074818/205908118-e8363dda-8ce0-4a2a-aadd-81aef7de84a2.png)
2. Try to delete the transform - you can actually see the space here at the end if you look closely
![image](https://user-images.githubusercontent.com/15074818/205905312-c1428d4e-3119-4a32-9fbd-256e9e5ecc3b.png)
3. Dashboard will report a "successful" deletion, the Dashboard API will respond with "success: true" but the same old list
![image](https://user-images.githubusercontent.com/15074818/205905628-48bbd28b-4780-4615-b60b-bc14efdb650f.png)
4. if calling the endpoint normally and parsing the JSON response, you will notice there is an "extra space" at the end of the name
![image](https://user-images.githubusercontent.com/15074818/205905762-e7fcc65a-2c05-4c8d-8607-33fcf365d1d2.png)
5. If trying to open the damaged transform from dashboard by clicking on it, a "not found" error ensues
![image](https://user-images.githubusercontent.com/15074818/205906114-672bff2e-d7ce-45ea-a149-2b0a202bd900.png)
6. When trying to fetch via API, there is no way of adding the extra space at the end, even by encoding
![image](https://user-images.githubusercontent.com/15074818/205907405-31f77797-5a53-43c3-8f91-cfd3075ad7f9.png)

**Expected behavior**
- Not being able to create a new transform with an ID with spaces (seems to be already okay)
- Being able to delete that old transform someway (can't, both from dashboards or regular APIs)

**OpenSearch Version**
AWS OpenSearch Service 2.3

**Dashboards Version**
AWS OpenSearch Service 2.3 (Embedded)

**Plugins**
AWS OpenSearch Service 2.3

**Screenshots**
Posted in replication steps

**Host/Environment (please complete the following information):**
- Windows 11 / Chrome (not applicable)

**Note**:
Any suggestion on at least how to fix this behaviour on my cluster?

**Comment by kavilla** [comment]
Transferring to ISM plugin.

cc: @zhongnansu @joshuarrrr
