### ISSUE TITLE
Admin UI for data stream

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/index-management-dashboards-plugin#464]
**Is your feature request related to a problem?**
Data streams management do not have a dedicate page for now and there are so much difference between indices and data streams. So we'd like to introduce a management flow for data streams to help users better manage their data streams.

**What solution would you like?**
Add new pages for create/read/update/delete data streams.

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
No

**Comment by Angie-Zhang** [comment]
Replaced label v2.6.0 with v2.x due to the 2.6.0 release code cut off.
