### ISSUE TITLE
Admin UI of force_merge

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/index-management-dashboards-plugin#465]
**Is your feature request related to a problem?**
User can only apply force merge action by API now so we'd like to add a page to help users force merge their indexes.

**What solution would you like?**
Add new page for force merge.

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
No

**Comment by Angie-Zhang** [comment]
Replaced label v2.6.0 with v2.x due to the 2.6.0 release code cut off.
