### ISSUE TITLE
[FEATURE] Index Management - Create index: Improve json editor validation 

### ISSUE THREAD

**Issue by xluo-aws** [opensearch-project/index-management-dashboards-plugin#545]
**Is your feature request related to a problem?**
When user use json editor to add index mapping, if the content is not compatible with visual editor, there is no warning so user is not aware that what they enter will not show up in visual editor, this may cause confusion even the data is not lost.

**What solution would you like?**
We will display a warning message that tells which line has this problem.

https://user-images.githubusercontent.com/13493605/211690814-be6aa7c4-ca87-44cb-8c1f-a1b3bb82aa27.mp4

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
No

**Comment by Angie-Zhang** [comment]
Replaced label v2.6.0 with v2.x due to the 2.6.0 release code cut off.

**Comment by hdhalter** [comment]
Hi @SuZhou-Joe , does this feature require documentation for 2.7?

**Comment by SuZhou-Joe** [comment]
Nope, it's an enhancement and do not have any impact on user flow.

**Comment by SuZhou-Joe** [comment]
> Hi @SuZhou-Joe , does this feature require documentation for 2.7?

No, it's an enhancement and do not have any impact on user flow.
