### ISSUE TITLE
[FEATURE] Rename indices to indexes

### ISSUE THREAD

**Issue by kamingleung** [opensearch-project/index-management-dashboards-plugin#637]
**Is your feature request related to a problem?**
Replace any references of `indices` to `indexes` on the Index Management UI to align with OpenSearch documentation and writing style.

Areas and underlaying flows that need renaming:
- State management policies
- Policy managed indices
- Indices
- Rollup jobs
- Transform jobs

For example:
![image](https://github.com/opensearch-project/index-management-dashboards-plugin/assets/3692324/3b287d7a-0cbe-4f3b-92fc-6b4afc5574fd)

**Comment by kamingleung** [comment]
@praveensameneni @AWSHurneyt Is this something we can look into for 2.9?

**Comment by AWSHurneyt** [comment]
CC: @getsaurabh02

**Comment by MansiShinde** [comment]
Hi @bowenlan-amzn, can you assign me this issue?
