### ISSUE TITLE
Fix cypress ISM retry test

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/index-management-dashboards-plugin#70]
Cypress ISM retry test breaks after backend security changes. Refer to comment [here](https://github.com/opensearch-project/index-management-dashboards-plugin/pull/69#discussion_r695932250) 

We need to use new way to cause a failed managed job and retry it.

**Comment by dbbaughe** [comment]
Picking this up as part of: https://github.com/opensearch-project/index-management-dashboards-plugin/issues/120
