### ISSUE TITLE
[FEATURE] Make background color in "state" block of edit index management not hardcoded

### ISSUE THREAD

**Issue by richardtruefort** [opensearch-project/index-management-dashboards-plugin#778]
**Is your feature request related to a problem?**
1. Go To Index Management
2. Navigate To Index Policies
3. Select a policy and edit via policy editor
4. Go to the States

The background color of "states" is hardcoded to a whitish color, which will clash with overall theme color of UI when in dark mode.

![image](https://github.com/opensearch-project/index-management-dashboards-plugin/assets/135068841/784c476d-3fa6-40b1-ab72-f7c303a915b0)

**What solution would you like?**
Color of 'state' section appear to be hardcoded here:

https://github.com/opensearch-project/index-management-dashboards-plugin/blob/main/public/pages/VisualCreatePolicy/components/States/State.tsx

line 105:

`<EuiFlexGroup direction="column" style={{ backgroundColor: "#f8f9fc" }}>`

It would be nice if this could be changed to either dynamically adjust according to "main" theme of the UI (i.e darkMode)

**Comment by jjafarovs** [comment]
Could I be assigned this issue? Thanks.

**Comment by wrch0712** [comment]
Could I be assigned this issue? Thanks.
