### ISSUE TITLE
[BUG] Missing cancel button in Change policy page

### ISSUE THREAD

**Issue by kamingleung** [opensearch-project/index-management-dashboards-plugin#840]
**What is the bug?**
In the 'Change policy' page, users don't have a clear path to leave the page if they decided not to change policies.
![image](https://github.com/opensearch-project/index-management-dashboards-plugin/assets/3692324/0c9bda85-749d-4a48-9c31-d1ead7e0097c)

**How can one reproduce the bug?**
1. Go to 'Index Management'
2. Go to 'Policy managed indexes'
3. Click on 'Change policy' button

**What is the expected behavior?**
Next to the 'Change' button, there should be a button called Cancel that will take users back to the 'Policy managed indexes' page.

Use [OuiButtonEmpty](https://oui.opensearch.org/1.2/#/navigation/button#empty-button), Primary for the Cancel button:
![image](https://github.com/opensearch-project/index-management-dashboards-plugin/assets/3692324/268c088f-cc78-4f5e-a3fb-fd444b39660d)

**Comment by kohinoor98** [comment]
Hi @bowenlan-amzn 

Please could. you assign this to me?

**Comment by bowenlan-amzn** [comment]
Thank you @kohinoor98 !
