### ISSUE TITLE
[Flaky Test] indices_spec.js

### ISSUE THREAD

**Issue by kohinoor98** [opensearch-project/index-management-dashboards-plugin#937]
**What is the bug?**
[A clear and concise description of the bug.](https://github.com/opensearch-project/index-management-dashboards-plugin/actions/runs/6877320964/job/18704705597?pr=920)

**What is the expected behavior?**
The test cases should pass

**Comment by dblock** [comment]
[Triage -- attendees [1](https://github.com/dblock), [2](https://github.com/peternied), [3](https://github.com/reta), [4](https://github.com/krisfreedain), [5](https://github.com/Getsaurabh02), [6](https://github.com/gkamat), [7](https://github.com/scrawfor99)]

Is this still a problem @kohinoor98?

**Comment by kohinoor98** [comment]
Hi @dblock 

I have not checked; based on the [commit history](https://github.com/opensearch-project/index-management-dashboards-plugin/commits/main/cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js), it might have been fixed. Unfortunately, the `Cypress E2E Tests Log` has expired. As there are no mentions of this issue in any of the PRs it is possible that this flaky test was not encountered again.
