### ISSUE TITLE
[BUG] Release 1.0.1 branch contains changes that belongs to next release.

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/index-management-dashboards-plugin#94]
**Describe the bug and impact**
The new feature of Index State Management (ISM) dashboard (aim for 1.1 release) has been partially leaked out in 1.0.1 patch release. 

The new feature is to provide a UI workflow to create/view ISM policy compared to previously only a JSON editor provided. The old JSON editor way of creating/viewing ISM policy is still functional. But the new way is problematic and not functional yet, so user will only see a broken ISM UI workflow in our 1.0.1 release. The fully functional version should come out with 1.1 release on Oct. 5th.

**Root cause**

When the engineer was doing the 1.0.1 patch release, there wasn't an existing 1.0 branch in this plugin. So the engineer cut the 1.0 branch directly from the HEAD of main branch which can be easily done by 1-click through the GitHub website. However, the main branch has already been added quite a few new changes for the next 1.1 release. The right way to cut the 1.0 branch in this case is to cut it from [the 1.0.0 release commit](https://github.com/opensearch-project/index-management-dashboards-plugin/commit/6ab1df211d9ac417be840acdb1db06a498e11779) but not HEAD of the main branch.

**TO-DO**

- [x] Revert those leaking commits on the 1.0 branch.

**Reflection**

If an existing 1.0 branch has been there during 1.0.1 release, we shouldn't end up with such an awkward problem now. To make sure this not happening again, a more formalized way for cutting the new release branch should be adopted:

1. One week before the new release code freeze date, the new release branch of plugin should be cut from the main branch and provided to infrastructure team's bundle and testing workflow. If any new feature need to add in this new release, we can cherry-pick it from the main branch then.

2. On the new release code freeze date, a comparison between the new release branch and previous release tag should be reviewed by other team members. This is to make sure all the new releasing changes compared to last release are exactly what we want. Taking this 1.1 release as an example, we can create [this comparison between 1.1 branch and 1.0.1.0 release tag](https://github.com/opensearch-project/index-management-dashboards-plugin/compare/1.0.1.0...1.1).

**Comment by dbbaughe** [comment]
@bowenlan-amzn Can we close this?
